/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by QuickBase Type Builder.
 * DO NOT MODIFY IT BY HAND. Instead, modify your QuickBase config,
 * and re-run `pnpm generate` to regenerate this file.
 */

// Field ID mappings
export const FieldMappings: Record<string, Record<string, Record<string, number>>> = {
  "BgSoftware": {
    "software": {
      "name": 6,
      "type": 7,
      "status": 15,
      "primaryuse": 10,
      "bgownerfullname": 16,
      "bgowneremail": 17,
      "bgownerdepartment": 18,
      "vendor": 8,
      "vendorcontactname": 11,
      "vendorcontactemail": 12,
      "website": 14,
      "notes": 13,
      "bgowner": 9,
      "conversationrecords": 19,
      "addconversation": 20,
      "deploymentrecords": 21,
      "adddeployment": 22
    },
    "employees": {
      "entraid": 6,
      "firstName": 7,
      "lastName": 8,
      "fullname": 9,
      "title": 10,
      "department": 11,
      "office": 12,
      "email": 13,
      "phone": 14,
      "softwarerecords": 15,
      "addsoftware": 16,
      "deploymentrecords": 17,
      "adddeployment": 18
    },
    "conversations": {
      "softwarename": 12,
      "decisionmade": 11,
      "decision": 9,
      "comments": 10
    },
    "projects": {
      "projectName": 8,
      "regionname": 9,
      "divisionname": 10,
      "marketsectorname": 11,
      "address": 15,
      "street1": 16,
      "street2": 17,
      "city": 18,
      "stateregion": 19,
      "postalcode": 20,
      "country": 21,
      "deploymentrecords": 22,
      "adddeployment": 23
    },
    "projectdeployments": {
      "projectName": 14,
      "softwarename": 15,
      "bgprojectcontactfullname": 16,
      "bgprojectcontactemail": 17,
      "comments": 12,
      "bgprojectcontact": 10
    }
  }
};

// Table ID mappings  
export const TableMappings: Record<string, Record<string, string>> = {
  "BgSoftware": {
    "software": "bvba8quar",
    "employees": "bvba8quas",
    "conversations": "bvba8qubc",
    "projects": "bvba8qube",
    "projectdeployments": "bvba8quc2"
  }
};

// Field name to ID mapping utility
export function getFieldId(
  app: string,
  table: string,
  fieldName: string
): number {
  const appMappings = FieldMappings[app];
  if (!appMappings) return 3; // Default to record ID
  
  const tableMappings = appMappings[table];
  if (!tableMappings) return 3; // Default to record ID
  
  const fieldId = tableMappings[fieldName];
  return typeof fieldId === 'number' ? fieldId : 3; // Default to record ID
}

// Table ID mapping
export function getTableId(
  app: string,
  table: string
): string {
  const appMappings = TableMappings[app];
  if (!appMappings) return String(table);
  
  const tableId = appMappings[table];
  return typeof tableId === 'string' ? tableId : String(table);
}
